version: '3'
services:
 web:
  image: nginx
 db: 
  image: mysql
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=5A>yRMwzS::cLF}G
  - MYSQL_USER=elena.bozharova
  - MYSQL_PASSWORD=5A>yRMwzS::cLF}G
  - MYSQL_DATABASE=my-sql-db