//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetshopMicroservice.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Petshop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Petshop()
        {
            this.Commenteds = new HashSet<Commented>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> ReviewCount { get; set; }
        public string Category { get; set; }
        public string Attributes { get; set; }
        public string Address { get; set; }
        public string PlusCode { get; set; }
        public string Website { get; set; }
        public string PhoneNumber { get; set; }
        public string SaturdayWorkingHours { get; set; }
        public string SundayWorkingHours { get; set; }
        public string MondayWorkingHours { get; set; }
        public string TuesdayWorkingHours { get; set; }
        public string WednesdayWorkingHours { get; set; }
        public string ThursdayWorkingHours { get; set; }
        public string FridayWorkingHours { get; set; }
        public string ImgURL { get; set; }
        public bool IsClaimed { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Commented> Commenteds { get; set; }
    }
}
